
export const teamColors2023 = [
  "",
  "#F91536",
  "#F58020",
  "#3671C6",
  "#79edd6",
  "#2293D1",
  "#37BEDD",
  "#B6BABD",
  "#5E8FAA",
  "#C92D4B",
  "#22594a",
]
export const teams2023 = [
  "",
  "Ferrari",
  "McLaren",
  "Red Bull",
  "Mercedes",
  "Alpine",
  "Williams",
  "Haas",
  "AlphaTauri",
  "Alfa Romeo",
  "Aston Martin",
  "PREMA Racing",
  "Invicta Virtuosi Racing",
  "Rodin Carlin",
  "Hitech Pulse-Eight",
  "ART Grand Prix",
  "MP Motorsport",
  "PHM Racing by Charouz",
  "DAMS",
  "Campos Racing",
  "Van Amersfoort Racing",
  "Trident",
  "PREMA Racing",
  "Trident",
  "ART Grand Prix",
  "Hitech Pulse-Eight",
  "Van Amersfoort Racing",
  "MP Motorsport",
  "Campos Racing",
  "Rodin Carlin",
  "Jenzer Motorsport",
  "PHM Racing by Charouz",
];