
export const teamColors2023 = [
  "",
  "#F91536",
  "#F58020",
  "#3671C6",
  "#79edd6",
  "#2293D1",
  "#37BEDD",
  "#B6BABD",
  "#5E8FAA",
  "#C92D4B",
  "#22594a",
]
export const teams2023 = [
  "",
  "Ferrari",
  "McLaren",
  "Red Bull",
  "Mercedes",
  "Alpine",
  "Williams",
  "Haas",
  "AlphaTauri",
  "Alfa Romeo",
  "Aston Martin",

  "PREMA (F2)",
  "Invicta Virtuosi",
  "Rodin Carlin (F2)",
  "Hitech (F2)",
  "ART Grand Prix (F2)",
  "MP Motorsport (F2)",
  "PHM (F2)",
  "DAMS",
  "Campos (F2)",
  "Van Amersfoort (F2)",
  "Trident (F2)",

  "PREMA (F3)",
  "Trident (F3)",
  "ART Grand Prix (F3)",
  "Hitech (F3)",
  "Van Amersfoort (F3)",
  "MP Motorsport (F3)",
  "Campos (F3)",
  "Rodin Carlin (F3)",
  "Jenzer Motorsport",
  "PHM (F3)",
];

/*

  "PREMA Racing (F2)",
  "Invicta Virtuosi Racing",
  "Rodin Carlin (F2)",
  "Hitech Pulse-Eight (F2)",
  "ART Grand Prix (F2)",
  "MP Motorsport (F2)",
  "PHM Racing by Charouz (F2)",
  "DAMS",
  "Campos Racing (F2)",
  "Van Amersfoort Racing (F2)",
  "Trident (F2)",

  "PREMA Racing (F3)",
  "Trident (F3)",
  "ART Grand Prix (F3)",
  "Hitech Pulse-Eight (F3)",
  "Van Amersfoort Racing (F3)",
  "MP Motorsport (F3)",
  "Campos Racing (F3)",
  "Rodin Carlin (F3)",
  "Jenzer Motorsport",
  "PHM Racing by Charouz (F3)",
 */