export const getDriverCode = (loc) => {
  return loc.replace("[DriverCode_", "").replace("]", "").toUpperCase();
}

export const weekendStages = [
  "Day 1",
  "Practice 1",
  "Practice 2",
  "Day 2",
  "Practice 3",
  "Qualifying 1",
  "Qualifying 2",
  "Qualifying 3",
  "Day 3",
  "Race",
  "Race End",
  "Race End",
  "Race End",
]
export const circuitNames = [
  "",
  "Melbourne",
  "Silverstone",
  "Jeddah",
  "Budapest",
  "Spa-Francorchamps",
  "Monza",
  "Singapore",
  "Russia",
  "Suzuka",
  "Mexico City",
  "Austin",
  "Sakhir",
  "São Paulo",
  "Yas Island",
  "Miami Gardens",
  "Zandvoort",
  "Imola",
  "China",
  "Baku",
  "Barcelona",
  "Monte Carlo",
  "Montréal",
  "Le Castellet",
  "Spielberg",
  "Losail",
  "Las Vegas",
]
export const countryNames = [
  "",
  "Australia",
  "Great Britain",
  "Saudi Arabia",
  "Hungary",
  "Belgium",
  "Italy",
  "Singapore",
  "Russia",
  "Japan",
  "Mexico",
  "United States",
  "Bahrain",
  "Brazil",
  "Abu Dhabi",
  "United States",
  "Netherlands",
  "Italy",
  "China",
  "Azerbaijan",
  "Spain",
  "Monaco",
  "Canada",
  "France",
  "Austria",
  "Qatar",
  "United States",
]