export const PerformanceStatTypes = [
  "Chassis",
  "FrontWingAndNose",
  "Cornering",
  "Braking",
  "Control",
  "Smoothness",
  "Adaptability",
  "Overtaking",
  "Defence",
  "Acceleration",
  "Accuracy",
  "Training",
  "PitCrewManagement",
  "Friendliness",
  "RearWing",
  "SidePods",
  "FloorAndDiffuser",
  "Suspension",
  "RollReduction",
  "Cooling",
  "DRS",
  "ImprovedDevelopment",
  "Aptitude",
  "Leadership",
  "Processes",
  "Feedback",
  "HighSpeedDownforce",
  "MediumSpeedDownforce",
  "LowSpeedDownforce",
  "Drag",
  "AirflowManagement",
  "Sensitivity",
  "FrontAndRearJacks",
  "Tyres",
  "WingAdjustmentAndReplacement",
  "CarRelease",
  "Speed",
  "Consistency",
  "Fatigue",
  "CarSetup",
  "WheelGun",
  "WheelOff",
  "WheelOn",
  "Composure",
];
export const mailSenders = {
  "STAFF_TYPE_5": "Team Principal",
  "MAIL_SENDER_ACCOUNTANT_NEIL": "Neil Baldr",
  "MAIL_SENDER_AERO_ENGINEER_VERA": "Vera Bidane",
  "MAIL_SENDER_BOARD_REP_PATRICK": "Patrick Stafford",
  "MAIL_SENDER_BOARD_REPRESENTATIVE": "Board Representative",
  "MAIL_SENDER_CHIEF_MEDICAL_OFFICER": "Chief Medical Officer",
  "MAIL_SENDER_DEP_TEAM_P_JANEY": "Audrey Mensah",
  "MAIL_SENDER_DEPUTY_TEAM_PRINCIPAL": "Senior Engineer",
  "MAIL_SENDER_DTS": "Helena Jones",
  "MAIL_SENDER_DTS_SHOWRUNNER": "Drive to Survive Showrunner",
  "MAIL_SENDER_F1_IN_SCHOOLS": "Percy Amato",
  "MAIL_SENDER_F1COM_REPORTER": "Formula1.com Reporter",
  "MAIL_SENDER_F1JOURNALIST": "F1® Journalist",
  "MAIL_SENDER_FACILITIES_CLAIRE": "Claire Hart",
  "MAIL_SENDER_FACILITIES_MANAGER": "Facilities Manager",
  "MAIL_SENDER_FINANCIAL_REGS": "Formula 1®",
  "MAIL_SENDER_HOSPITALITY_COORDINATOR": "Hospitality Coordinator",
  "MAIL_SENDER_HR_LEAD_THEO": "Théo Burnell",
  "MAIL_SENDER_MEDICAL_TITUS": "Titus Kasey",
  "MAIL_SENDER_ORGANISATION_FINANCIAL_REGS": "Financial Regulations",
  "MAIL_SENDER_ORGANISATION_REGULATIONS": "Formula 1®",
  "MAIL_SENDER_PERSONNEL_MARIA": "Maria Zilpah",
  "MAIL_SENDER_PERSONNEL_OFFICER": "Personnel Officer",
  "MAIL_SENDER_PIT_CREW_LEAD": "Pit Crew Lead",
  "MAIL_SENDER_PIT_CREW_ROSHNI": "Roshni Patel",
  "MAIL_SENDER_POSITION": "{Position}, {Team}",
  "MAIL_SENDER_REPORTER_1": "Michael Loom",
  "MAIL_SENDER_REPORTER_2": "Sandra Maddox",
  "MAIL_SENDER_REPORTER_IAN": "Michael Loom",
  "MAIL_SENDER_REPORTER_SAMANTHA": "Sandra Maddox",
  "MAIL_SENDER_RND_ENGINEER_FELICITY": "Felicity F. Seer",
  "MAIL_SENDER_SCOUTING_FRED": "Fred Gill",
  "MAIL_SENDER_SCOUTING_LEAD": "Scouting Lead",
  "MAIL_SENDER_SENIOR_ACCOUNTANT": "Senior Accountant",
  "MAIL_SENDER_SENIOR_AERODYNAMICS_ENGINEER": "Senior Aerodynamics Engineer",
  "MAIL_SENDER_SENIOR_R&D_ENGINEER": "Senior R&D Engineer",
  "MAIL_SENDER_SPONSOR": "Molly Tander",
  "MAIL_SENDER_SPONSOR_DIRECTOR": "Sponsorships Director",
  "MAIL_SENDER_SPORTING_DIRECTOR": "Sporting Director",
  "MAIL_SENDER_SUBL_HR_LEAD": "HR Lead",
  "MAIL_SENDER_TUTORIAL": "Audrey Mensah",
  "F1_REGULATIONS_SENDER": "Regulations Manager",
};

export const localeStaffStats = {
  "STAFF_STAT_0": "Chassis",
  "STAFF_STAT_0_DESCRIPTION": "The ability to optimise the mechanical design of the chassis. A higher rating provides a greater bonus to all car part attributes when designing a new chassis.",
  "STAFF_STAT_1": "Front Wing",
  "STAFF_STAT_10": "Accuracy",
  "STAFF_STAT_10_DESCRIPTION": "The ability to follow the racing line as accurately as possible. This reduces the chance of a driver losing time or their car taking damage from running wide while racing.",
  "STAFF_STAT_11": "Training",
  "STAFF_STAT_11_DESCRIPTION": "The ability to efficiently develop the skill of team mechanics. The higher the rating, the faster the pit crew develop through training sessions, and the less performance they lose between seasons.",
  "STAFF_STAT_12": "Pit Crew Management",
  "STAFF_STAT_12_DESCRIPTION": "The ability to effectively communicate with and prepare the pit crew during a race.  A higher rating means faster pit stops for the race engineer’s paired driver.",
  "STAFF_STAT_13": "Communication",
  "STAFF_STAT_13_DESCRIPTION": "The ability to communicate clearly and effectively. A higher rating means faster affinity growth between the race engineer and their paired driver.",
  "STAFF_STAT_14": "Rear Wing",
  "STAFF_STAT_14_DESCRIPTION": "The ability to optimise the mechanical design of the rear wing. A higher rating means a greater bonus to all car part attributes when designing a new rear wing.",
  "STAFF_STAT_15": "Sidepods",
  "STAFF_STAT_15_DESCRIPTION": "The ability to optimise the mechanical design of the sidepods. A higher rating means a greater bonus to all car part attributes when designing new sidepods.",
  "STAFF_STAT_16": "Underfloor",
  "STAFF_STAT_16_DESCRIPTION": "The ability to optimise the mechanical design of the underfloor. A higher rating means a greater bonus to all car part attributes when designing a new underfloor.",
  "STAFF_STAT_17": "Suspension",
  "STAFF_STAT_17_DESCRIPTION": "The ability to optimise the mechanical design of the suspension. A higher rating means a greater bonus to all car part attributes when designing a new suspension system.",
  "STAFF_STAT_18": "DEPRECATED - Roll Reduction",
  "STAFF_STAT_18_DESCRIPTION": "DEPRECATED - The ability to optimise the mechanical design of car parts to reduce roll while cornering. A higher rating means a greater bonus to roll reduction when designing car parts.",
  "STAFF_STAT_19": "Cooling",
  "STAFF_STAT_19_DESCRIPTION": "The ability to optimise the aerodynamic design of car parts to improve engine or brake cooling. A higher rating means a greater bonus when designing car parts that direct airflow for cooling purposes.",
  "STAFF_STAT_1_DESCRIPTION": "The ability to optimise the mechanical design of the front wing. A higher rating means a greater bonus to all car part attributes when designing a new front wing.",
  "STAFF_STAT_2": "Cornering",
  "STAFF_STAT_20": "DRS Delta",
  "STAFF_STAT_20_DESCRIPTION": "The ability to optimise the aerodynamic design of car parts that improve the DRS delta, which measures the speed boost provided by the Drag Reduction System (DRS). A higher rating means a greater bonus when designing car parts that affect the DRS delta.",
  "STAFF_STAT_21": "Improved Development",
  "STAFF_STAT_21_DESCRIPTION": "TODO - Improved Development Desc",
  "STAFF_STAT_22": "Aptitude",
  "STAFF_STAT_22_DESCRIPTION": "The ability to help team mechanics reach their full potential. A higher rating means a higher upper limit to the pit crew’s potential skill.\r\n\r\nThe pit crew’s attributes can only improve up to the Sporting Director’s aptitude.",
  "STAFF_STAT_23": "Leadership",
  "STAFF_STAT_23_DESCRIPTION": "The ability to manage a team through high-pressure situations. A higher rating means a greater chance to minimise the delay from pit stop mistakes.",
  "STAFF_STAT_24": "Processes",
  "STAFF_STAT_24_DESCRIPTION": "The ability to develop and refine efficient workflows. The higher the rating, the less fatigue that the pit crew gains from race weekends and training sessions.",
  "STAFF_STAT_25": "Feedback",
  "STAFF_STAT_25_DESCRIPTION": "The ability to give and understand feedback on the car's set-up during practice sessions. A higher rating means quicker feedback on improving the car set-up during practice.",
  "STAFF_STAT_26": "High Speed Downforce",
  "STAFF_STAT_26_DESCRIPTION": "The ability to optimise the aerodynamic design of car parts that generate downforce at high speeds. A higher rating means a greater bonus when designing car parts that generate high speed downforce.",
  "STAFF_STAT_27": "Medium Speed Downforce",
  "STAFF_STAT_27_DESCRIPTION": "The ability to optimise the aerodynamic design of car parts that generate downforce at medium speeds A higher rating means a greater bonus when designing car parts that generate medium speed downforce.",
  "STAFF_STAT_28": "Low Speed Downforce",
  "STAFF_STAT_28_DESCRIPTION": "The ability to optimise the aerodynamic design of car parts that generate downforce at low speeds. A higher rating means a greater bonus when designing car parts that generate low speed downforce.",
  "STAFF_STAT_29": "Drag Reduction",
  "STAFF_STAT_29_DESCRIPTION": "The ability to optimise the aerodynamic design of car parts to reduce drag and increase top speeds. A higher rating means a greater bonus when designing car parts that affect the car’s overall drag.",
  "STAFF_STAT_2_DESCRIPTION": "The ability to maintain speed through corners. This allows the driver to go faster through all corners to improve lap times, and reduces the chance of them running wide or spinning when they do.",
  "STAFF_STAT_3": "Braking",
  "STAFF_STAT_30": "Airflow Management",
  "STAFF_STAT_30_DESCRIPTION": "The ability to optimise the aerodynamic design of car parts to better guide and condition airflow. A higher rating means a greater bonus when designing car parts that shape airflow over the car's front or middle.",
  "STAFF_STAT_31": "Airflow Sensitivity",
  "STAFF_STAT_31_DESCRIPTION": "The ability to optimise the aerodynamic design of car parts to improve cornering performance in the turbulent, dirty air left in the wake of other cars. A higher rating means a greater bonus when designing car parts that improve sensitivity to dirty air.",
  "STAFF_STAT_32": "Front and Rear Jacks",
  "STAFF_STAT_32_DESCRIPTION": "Improves the speed of jacking the car up during a pit stop, and reduces the likelihood of jacks mistakes.\r\n\r\nJack delays have a moderate likelihood of occurring, but cost a short delay during pit stops.\r\n\r\nStrong training in using jacks will lead to a large reduction in all pit stop times.",
  "STAFF_STAT_33": "Tyre Changes",
  "STAFF_STAT_33_DESCRIPTION": "Improves the speed of replacing tyres during a pit stop and reduces the likelihood of tyre fitting mistakes.\r\n\r\nTyre change mistakes have a low likelihood of occurring, but cost a long delay during pit stops.\r\n\r\nStrong training in tyre change techniques will lead to a moderate reduction in all pit stop times, and a reduction in time taken to adjust a car’s toe-out, tyre camber, and anti-roll distribution set-up during practice sessions.",
  "STAFF_STAT_34": "Wing Adjustment",
  "STAFF_STAT_34_DESCRIPTION": "Improves the ability to replace the front wing during a pit stop, and reduces the likelihood of wing replacement mistakes. \r\n\r\nWing mistakes have a high likelihood of occurring when replacing the front wing, and cost a long delay during pit stops.\r\n\r\nTraining in this area has no impact on pit stops that don’t include a front wing replacement.",
  "STAFF_STAT_35": "Car Release",
  "STAFF_STAT_35_DESCRIPTION": "Reduces the chance of releasing a car too early or incorrectly during a pit stop.\r\n\r\nCar release mistakes have a high likelihood of occurring, and cost a moderate delay in pit stops.\r\n\r\nStrong training in car release techniques will lead to a small reduction in all pit stop times.",
  "STAFF_STAT_36": "Speed",
  "STAFF_STAT_36_DESCRIPTION": "The speed at which the Pit Stop is executed",
  "STAFF_STAT_37": "Consistency",
  "STAFF_STAT_37_DESCRIPTION": "The chance the Pit Crew will encounter an error during a Pit Stop",
  "STAFF_STAT_38": "Fatigue",
  "STAFF_STAT_38_DESCRIPTION": "The energy level of the Pit Crew",
  "STAFF_STAT_39": "Car Setup",
  "STAFF_STAT_39_DESCRIPTION": "TODO - Car Setup Desc",
  "STAFF_STAT_3_DESCRIPTION": "The ability to brake more efficiently. This allows drivers to brake later when approaching corners to improve lap times without running wide or causing racing incidents.",
  "STAFF_STAT_4": "Control",
  "STAFF_STAT_40": "Wheel Gun",
  "STAFF_STAT_40_DESCRIPTION": "TODO - Wheel Gun Desc",
  "STAFF_STAT_41": "Wheel Off",
  "STAFF_STAT_41_DESCRIPTION": "TODO - Wheel Off Desc",
  "STAFF_STAT_42": "Wheel On",
  "STAFF_STAT_42_DESCRIPTION": "TODO - Wheel On Desc",
  "STAFF_STAT_43": "Composure",
  "STAFF_STAT_43_DESCRIPTION": "The ability to remain focused in high-stress environments, and to keep others focused. A higher rating means less driver confidence loss from negative events on track, and more driver confidence gain from positive events on track.",
  "STAFF_STAT_4_DESCRIPTION": "The ability to prevent racing incidents. This reduces the likelihood of the driver causing lock-ups, spins, crashes, or running wide.",
  "STAFF_STAT_5": "Smoothness",
  "STAFF_STAT_5_DESCRIPTION": "The ability to reduce tyre wear while racing. This allows a driver to push harder and run longer stints on each set of tyres.",
  "STAFF_STAT_6": "Adaptability",
  "STAFF_STAT_6_DESCRIPTION": "The ability to adapt to poor weather on track. This improves the driver’s acceleration and cornering speed on tyres not suited to wetter track levels.",
  "STAFF_STAT_7": "Overtaking",
  "STAFF_STAT_7_DESCRIPTION": "The ability to overtake other drivers. This allows the driver to attempt and successfully complete more overtakes while racing, and lowers the chance of causing a racing incident when they do.",
  "STAFF_STAT_8": "Defending",
  "STAFF_STAT_8_DESCRIPTION": "The ability to defend a position while racing. This reduces the chance that another driver will be able to successfully overtake.",
  "STAFF_STAT_9": "Reactions",
  "STAFF_STAT_9_DESCRIPTION": "The ability to respond to events at high speed. This allows the driver to accelerate faster out of corners, and to pull away faster when the lights go out at the start of the race.",
}