
export const teamColors2023 = [
  "",
  "#F91536",
  "#F58020",
  "#3671C6",
  "#79edd6",
  "#2293D1",
  "#37BEDD",
  "#B6BABD",
  "#5E8FAA",
  "#C92D4B",
  "#22594a",
]

export const teamColors2024 = [
  "",
  "#F91536",
  "#F58020",
  "#3671C6",
  "#79edd6",
  "#2293D1",
  "#37BEDD",
  "#B6BABD",
  "#5E8FAA",
  "#C92D4B",
  "#22594a",
]

export const teams2023 = [
  "",
  "Ferrari",
  "McLaren",
  "Red Bull",
  "Mercedes",
  "Alpine",
  "Williams",
  "Haas",
  "AlphaTauri",
  "Alfa Romeo",
  "Aston Martin",


  "PREMA Racing",
  "Invicta Virtuosi Racing",
  "Rodin Carlin",
  "Hitech Pulse-Eight",
  "ART Grand Prix",
  "MP Motorsport",
  "PHM Racing by Charouz",
  "DAMS",
  "Campos Racing",
  "Van Amersfoort Racing",
  "Trident",

  "PREMA Racing F3",
  "Trident F3",
  "ART Grand Prix F3",
  "Hitech Pulse-Eight F3",
  "Van Amersfoort Racing F3",
  "MP Motorsport F3",
  "Campos Racing F3",
  "Rodin Carlin F3",
  "Jenzer Motorsport",
  "PHM Racing by Charouz F3",
];

export const teams2024 = [
  "",
  "Ferrari",
  "McLaren",
  "Red Bull",
  "Mercedes",
  "Alpine",
  "Williams",
  "Haas",
  "RB",
  "Kick Sauber",
  "Aston Martin",

  "PREMA Racing",
  "Invicta Racing",
  "Rodin Motorsport",
  "Hitech Pulse-Eight",
  "ART Grand Prix",
  "MP Motorsport",
  "PHM AIX Racing",
  "DAMS Lucas Oil",
  "Campos Racing",
  "Van Amersfoort Racing",
  "Trident",

  "PREMA Racing F3",
  "Trident F3",
  "ART Grand Prix F3",
  "Hitech Pulse-Eight F3",
  "Van Amersfoort Racing F3",
  "MP Motorsport F3",
  "Campos Racing F3",
  "Rodin Motorsport F3",
  "Jenzer Motorsport",
  "PHM AIX Racing F3",

  "Custom Team",
];