export const valueToUnitValue = {
  0: x => x / 10,
  1: x => x / 10,
  2: x => x / 10,
  3: x => x / 10,
  4: x => x / 10,
  5: x => x / 10,

  6: x => Number((90 + x / 1000 * 10).toFixed(2)),

  7: x => Number((0.002 * x + 3).toFixed(3)),
  8: x => Number((0.002 * x + 5).toFixed(3)),
  9: x => Number((0.002 * x + 7).toFixed(3)),

  10: x => Number((90 + x / 1000 * 10).toFixed(2)),
  11: x => Number((85 - x / 1000 * 20).toFixed(2)),
  12: x => Number((70 + x / 1000 * 15).toFixed(2)),
  13: x => Number((x / 10).toFixed(3)),
  14: x => Number((85 + x / 1000 * 15).toFixed(2)),
  15: x => Number((40 + x / 1000 * 30).toFixed(2)),
}
export const valueToDeltaUnitValue = {
  0: 0.1,
  1: 0.1,
  2: 0.1,
  3: 0.1,
  4: 0.1,
  5: 0.1,

  6: 0.01,

  7: 0.002,
  8: 0.002,
  9: 0.002,

  10: 0.01,
  11: -0.02,
  12: 0.015,
  13: 0.1,
  14: 0.015,
  15: 0.03,
}

export const statRenderer = {
  0: x => `${(x).toFixed(2)}%`,
  1: x => `${(x).toFixed(2)}%`,
  2: x => `${(x).toFixed(2)}%`,
  3: x => `${(x).toFixed(2)}%`,
  4: x => `${(x).toFixed(2)}%`,
  5: x => `${(x).toFixed(2)}%`,

  6: x => `${(x).toFixed(2)}%`,

  7: x => `${(x).toFixed(2)} kN`,
  8: x => `${(x).toFixed(2)} kN`,
  9: x => `${(x).toFixed(2)} kN`,

  10: x => `${(x).toFixed(2)}%`,
  11: x => `${(x).toFixed(2)}%`,
  12: x => `${(x).toFixed(2)}%`,
  13: x => `${(x).toFixed(2)}%`,
  14: x => `${(x).toFixed(2)}%`,
  15: x => `${(x).toFixed(2)}%`,
}

export const PartNames = [
  "Engine",
  "ERS",
  "Gearbox",
  "Chassis",
  "Front Wing",
  "Rear Wing",
  "Sidepods",
  "Underfloor",
  "Suspension",
];

export const PartStats2023 = [
  {
    id: 0,
    category: "Powertrains",
    prefix: "PT",
    parts: [0, 1, 2],
    stats: [
      {id: "0_6", part: 0, stat: 6, digits: 0, displayDigits: 0, name: "Fuel Efficiency"},
      {id: "0_10", part: 0, stat: 10, digits: 0, displayDigits: 0, name: "Power"},
      {id: "0_11", part: 0, stat: 11, digits: 0, displayDigits: 0, name: "Power Loss Thr"},
      {id: "0_12", part: 0, stat: 12, digits: 0, displayDigits: 0, name: "Wear Resist"},
      {id: "0_14", part: 0, stat: 14, digits: 0, displayDigits: 0, name: "Thermal Resist"},
      {id: "1_15", part: 1, stat: 15, digits: 0, displayDigits: 0, name: "ERS Lifespan"},
      {id: "2_15", part: 2, stat: 15, digits: 0, displayDigits: 0, name: "Gearbox Lifespan"},
    ],
  },
  {
    id: 1,
    category: "Chassis",
    prefix: "C",
    parts: [3],
    stats: [
      {id: "3_4", part: 3, stat: 4, digits: 4, displayDigits: 4, name: "Drag Reduction"},
      {id: "3_5", part: 3, stat: 5, digits: 4, displayDigits: 4, name: "Engine Cooling"},
      {id: "3_13", part: 3, stat: 13, digits: 4, displayDigits: 4, name: "Airflow Middle"},
      {id: "3_15", part: 3, stat: 15, digits: 0, displayDigits: 0, name: "Lifespan",
        statRenderer: x => x + " km",
        valueToDeltaUnitValue: 270 / 100,
      },
    ],
  },
  {
    id: 2,
    category: "Front Wing",
    prefix: "FW",
    parts: [4],
    stats: [
      {id: "4_0", part: 4, stat: 0, digits: 4, displayDigits: 4, name: "Airflow Front"},
      {id: "4_1", part: 4, stat: 1, digits: 4, displayDigits: 4, name: "Air Sensitivity"},
      {id: "4_2", part: 4, stat: 2, digits: 4, displayDigits: 4, name: "Brake Cooling"},
      {id: "4_7", part: 4, stat: 7, digits: 4, displayDigits: 4, name: "Low Speed"},
      {id: "4_8", part: 4, stat: 8, digits: 4, displayDigits: 4, name: "Med Speed"},
      {id: "4_9", part: 4, stat: 9, digits: 4, displayDigits: 4, name: "High Speed"},
      {id: "4_15", part: 4, stat: 15, digits: 0, displayDigits: 0, name: "Lifespan",
        statRenderer: x => x + " km",
        valueToDeltaUnitValue: 375 / 100,
      },
    ],
  },
  {
    id: 3,
    category: "Rear Wing",
    prefix: "RW",
    parts: [5],
    stats: [
      {id: "5_1", part: 5, stat: 1, digits: 4, displayDigits: 4, name: "Air Sensitivity"},
      {id: "5_3", part: 5, stat: 3, digits: 4, displayDigits: 4, name: "DRS Delta"},
      {id: "5_4", part: 5, stat: 4, digits: 4, displayDigits: 4, name: "Drag Reduction"},
      {id: "5_7", part: 5, stat: 7, digits: 4, displayDigits: 4, name: "Low Speed"},
      {id: "5_8", part: 5, stat: 8, digits: 4, displayDigits: 4, name: "Med Speed"},
      {id: "5_9", part: 5, stat: 9, digits: 4, displayDigits: 4, name: "High Speed"},
      {id: "5_15", part: 5, stat: 15, digits: 0, displayDigits: 0, name: "Lifespan",
        statRenderer: x => x + " km",
        valueToDeltaUnitValue: 295 / 100,
      },
    ],
  },
  {
    id: 4,
    category: "Sidepods",
    prefix: "SP",
    parts: [6],
    stats: [
      {id: "6_0", part: 6, stat: 0, digits: 4, displayDigits: 4, name: "Airflow Front"},
      {id: "6_4", part: 6, stat: 4, digits: 4, displayDigits: 4, name: "Drag Reduction"},
      {id: "6_5", part: 6, stat: 5, digits: 4, displayDigits: 4, name: "Engine Cooling"},
      {id: "6_13", part: 6, stat: 13, digits: 4, displayDigits: 4, name: "AirFlowMiddle"},
      {id: "6_15", part: 6, stat: 15, digits: 0, displayDigits: 0, name: "Lifespan",
        statRenderer: x => x + " km",
        valueToDeltaUnitValue: 275 / 100,
      },
    ],
  },
  {
    id: 5,
    category: "Underfloor",
    prefix: "UF",
    parts: [7],
    stats: [
      {id: "7_1", part: 7, stat: 1, digits: 4, displayDigits: 4, name: "Air Sensitivity"},
      {id: "7_4", part: 7, stat: 4, digits: 4, displayDigits: 4, name: "Drag Reduction"},
      {id: "7_7", part: 7, stat: 7, digits: 4, displayDigits: 4, name: "Low Speed"},
      {id: "7_8", part: 7, stat: 8, digits: 4, displayDigits: 4, name: "Med Speed"},
      {id: "7_9", part: 7, stat: 9, digits: 4, displayDigits: 4, name: "High Speed"},
      {id: "7_15", part: 7, stat: 15, digits: 0, displayDigits: 0, name: "Lifespan",
        statRenderer: x => x + " km",
        valueToDeltaUnitValue: 290 / 100,
      },
    ],
  },
  {
    id: 6,
    category: "Suspension",
    prefix: "S",
    parts: [8],
    stats: [
      {id: "8_0", part: 8, stat: 0, digits: 4, displayDigits: 4, name: "Air Front"},
      {id: "8_2", part: 8, stat: 2, digits: 4, displayDigits: 4, name: "Brake Cooling"},
      {id: "8_4", part: 8, stat: 4, digits: 4, displayDigits: 4, name: "Drag Reduction"},
      {id: "8_7", part: 8, stat: 7, digits: 4, displayDigits: 4, name: "Low Speed"},
      {id: "8_8", part: 8, stat: 8, digits: 4, displayDigits: 4, name: "Med Speed"},
      {id: "8_9", part: 8, stat: 9, digits: 4, displayDigits: 4, name: "High Speed"},
      {id: "8_15", part: 8, stat: 15, digits: 0, displayDigits: 0, name: "Lifespan",
        statRenderer: x => x + " km",
        valueToDeltaUnitValue: 240 / 100,
      },
    ],
  },
];